"""race

Revision ID: 32eb115392e3
Revises: e65097fab244
Create Date: 2024-02-27 16:46:34.567116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32eb115392e3'
down_revision: Union[str, None] = 'e65097fab244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race',
    sa.Column('parent_race', sa.Integer(), nullable=True, foreign_key='race.id'),
    sa.Column('strength_modifier', sa.Integer(), nullable=False),
    sa.Column('dexterity_modifier', sa.Integer(), nullable=False),
    sa.Column('intellect_modifier', sa.Integer(), nullable=False),
    sa.Column('wisdom_modifier', sa.Integer(), nullable=False),
    sa.Column('charisma_modifier', sa.Integer(), nullable=False),
    sa.Column('expansion', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expansion'], ['expansion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_name'), 'race', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_name'), table_name='race')
    op.drop_table('race')
    # ### end Alembic commands ###
