"""functional change

Revision ID: 44fab12eac11
Revises: eeddf834afdb
Create Date: 2024-02-20 13:30:10.549709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fab12eac11'
down_revision: Union[str, None] = 'eeddf834afdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damage_type',
    sa.Column('expansion', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expansion'], ['expansion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_type_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('damage_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_type_name'))

    op.drop_table('damage_type')
    # ### end Alembic commands ###
