"""adding foreing key to class

Revision ID: 516db2e61f02
Revises: 912d84fe812e
Create Date: 2023-10-17 22:10:51.627801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516db2e61f02'
down_revision: Union[str, None] = '912d84fe812e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_character_sheet_race_race'), 'race', ['race'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_character_sheet_race_race'), type_='foreignkey')
        batch_op.drop_column('race')

    # ### end Alembic commands ###
