"""adding foreing key char for real

Revision ID: 912d84fe812e
Revises: eb95259471ae
Create Date: 2023-10-17 22:07:07.815829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912d84fe812e'
down_revision: Union[str, None] = 'eb95259471ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_character_sheet_class_id_class'), 'class', ['class_id'], ['id'])
        batch_op.drop_column('char_class')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('char_class', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_character_sheet_class_id_class'), type_='foreignkey')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###
