"""expansion_table

Revision ID: c9f76b5645b5
Revises: 
Create Date: 2024-02-19 18:22:32.679226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f76b5645b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expansion',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expansion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expansion_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expansion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expansion_name'))

    op.drop_table('expansion')
    # ### end Alembic commands ###
