"""following name conventions for race

Revision ID: cc84658ae14b
Revises: 516db2e61f02
Create Date: 2023-10-17 22:11:17.671256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc84658ae14b'
down_revision: Union[str, None] = '516db2e61f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_character_sheet_race_race', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_character_sheet_race_id_race'), 'race', ['race_id'], ['id'])
        batch_op.drop_column('race')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_character_sheet_race_id_race'), type_='foreignkey')
        batch_op.create_foreign_key('fk_character_sheet_race_race', 'race', ['race'], ['id'])
        batch_op.drop_column('race_id')

    # ### end Alembic commands ###
